### PR TITLE
# 164857228 Filter articles

### PR DESCRIPTION
**Pull request by Kimaiyo077**
**What does this PR do?**

Allows a user to filter through articles using article id, article title, and tags

**Tasks to be completed**

- [x] write unit tests 
- [x] implement filtering functionality for articles

**How can this be manually tested**

- Clone the repo and checkout the `ft/164857228-filter-articles ` branch

- Create and activate a virtual environment
```
$ virtualenv env
$ source env/bin/activate
```

- Install requirements
```
$ pip install -r requirements.txt
```

- Make migrations
```
$ python manage.py makemigrations
```

- Run migrations

```
$ python manage.py migrate
```

- Run the tests
```
python manage.py test
```
- Test via Postman 

`[POST] http://127.0.0.1:8000/api/users/`
     ```
     {
     "user": {
       	"email": "testuser@test.com",
		"password": "test2019",
		"username": "test"
    }
      }
     ```
- use the token from the signup to test the following endpoints 
`[POST] http://127.0.0.1:8000/api/articles`
```
{
	"article": {
		"title": "Test article",
		"description": "Testing2",
		"body": "This is the body of this article",
		"image_url": "http://www.google.com"
                "tags":["tags", "bot"] 
		}
	
}
```

  * Filter by author
    `[GET] http://127.0.0.1:8000/api/articles?author=test`

* Filter by tag
    `[GET] http://127.0.0.1:8000/api/articles?tags=tag`
   
  * Filter by article title
    `[GET] http://127.0.0.1:8000/api/articles?title=article`
**Replace title with a word that is part of an article's title, this returns all articles with the keyword in their title**    

   * All filters at once including pagination
  `[GET] http://127.0.0.1:8000/api/articles?page_size=3&author=test&title=article&tags=tags`

**Relevant Pivotal tracker stories** 
[#164857228](https://www.pivotaltracker.com/story/show/164857228)

### Screenshots

**Filter by author**
Screenshot from 2019-04-10 01-22-03

**Filter by title and author id**
Screenshot from 2019-04-10 01-22-46

**All filters**
Screenshot from 2019-04-10 01-23-11

### CODE REVIEW

**Review by misocho — APPROVED** [review]
Works as expected. Maybe we could also have a filter by tag. Good job.

**Review by bencyn — COMMENTED** [review]
works perfectly. However, when filtering by the author is it supposed to be  author_id or name/username. I noticed in the documentation it's by name. 

image

**Comment by Kimaiyo077** [comment]
> works perfectly. However, when filtering by the author is it supposed to be author_id or name/username. I noticed in the documentation it's by name.
> 
> image

You can now filter using author name instead of id

**Review by Tevinthuku — APPROVED** [review]
:+1: Awesome work

**Review by misocho — APPROVED** [review]

**Review by justMuriithi — APPROVED** [review]
Great work on the filters

**Review by miritih — APPROVED** [review]

**Pull request merged**
