### PR TITLE
#164857212 Return token on login and signup

### PR DESCRIPTION
**Pull request by Tevinthuku**
### What does this PR do?

This PR will add a `JWT` token to the payload of both login and signup

### Tasks to be completed?

- [x] - Write tests for getting a token upon signin and signup
- [x] - Create the token property on the user model.
- [x] - return a new token upon login
- [x] - return a new token upon signup
- [x] - create the auth backend that will check for the token before
performing requests
- [x] - Create a `base test` file which will provide a token to be used in different functionalities 

### How can this be manually tested?

- Clone the repo and checkout the `ft/164857212-return-jwt-on-auth` branch

- Create and activate a virtual environment
```
$ virtualenv env
$ source env/bin/activate
```

- Install requirements
```
$ pip install -r requirements.txt
```

- Make migrations
```
$ python manage.py makemigrations
```

- Run migrations

```
$ python manage.py migrate
```

- Start the app.
```
python manage.py runserver
```
- Open Postman and test the sign-up on `http://127.0.0.1:8000/api/users/` functionality. Use the following payload 
```
{
          "user": {
                "email": "premiermember@gmail.com",
                "username": "Premier Member",
                "password": "premiermember2019"
            }
        }
```

you will receive the following response.

```
{
    "user": {
        "email": "premiermember@gmail.com",
        "username": "Premier Member",
        "token": "tokenhere"
    }
}
```

- Testing login via  `http://127.0.0.1:8000/api/users/login/`
with the following payload 
```
{
            "user": {
                "email": "premiermember@gmail.com",
                "password": "premiermember2019"
            }
  }
```

we get the following result as a response.

```
{
    "user": {
        "email": "premiermember@gmail.com",
        "username": "Premier Member",
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InByZW1pZXJtZW1iZXJAZ21haWwuY29tIiwiZXhwIjoxNTUzNzY3MjE5fQ.yznDIGQEZ69EMisQWTCsHnZtGPDMpoRe1cCrpY4-4-4"
    }
}
```

### PT stories relevant to this PR?
[#164857212](https://www.pivotaltracker.com/n/projects/2321565/stories/164857212)

### CODE REVIEW

**Review by Kimaiyo077 — COMMENTED** [review]
Screenshot (50)
I am getting this error when I run the test.

**Review by martinMutuma — APPROVED** [review]
looks good, Though we should add more fields to the token like all those in the serializer class

**Comment by Kimaiyo077** [comment]
> Screenshot (50)
> I am getting this error when I run the test.

I think that behavior is there because we are using different platforms. I am on Windows and I presume you are using Linux. You should request another teammate to review while I change my OS to prevent this from happening again.

**Review by justMuriithi — APPROVED** [review]
PR looks good to go

**Comment by Tevinthuku** [comment]
@martinMutuma yes we could, but the authentication backend only looks out for the email field. So it can have more fields but they'll just be dangling and not really being used.

**Comment by miritih** [comment]
@Tevinthuku Kindly update the PR description with both the `register` and `login` endpoints, also include the `payload` to send when registering a user.

**Comment by Tevinthuku** [comment]
> @Tevinthuku Kindly update the PR description with both the `register` and `login` endpoints, also include the `payload` to send when registering a user.

Done :+1:

**Review by miritih — CHANGES_REQUESTED** [review]
From the `Readme`, the user response I should receive after either `login` or `register` is
 ```
{
  "user": {
    "email": "jake@jake.jake",
    "token": "jwt.token.here",
    "username": "jake",
    "bio": "I work at statefarm",
    "image": null
  }
}
```
The responnse you're returning is missing some data,`bio and image`.

**Comment by Tevinthuku** [comment]
@miritih  I have seen the responses, but as the app is right now we do not provide those fields. I think we will provide them when we are working on the profile functionality. If I add them now I'll just be adding null values or empty hardcoded strings. I can proceed with that.  What's your take on this?

image

**Comment by Tevinthuku** [comment]
Like when a user is signing into the app the user only provides the name, email address and password. Or do I work on the profile endpoint then add those fields?

**Comment by miritih** [comment]
> @miritih I have seen the responses, but as the app is right now we do not provide those fields. I think we will provide them when we are working on the profile functionality. If I add them now I'll just be adding null values. What's your take on this?
> 
> image

Makes sense,

**Review by miritih — APPROVED** [review]

**Pull request merged**
