### PR TITLE
#164857223 favorite/unfavorite articles

### PR DESCRIPTION
**Pull request by bencyn**
**What does this PR do?**

Allows an authenticated user to favorite and or unfavorite an article

**Tasks to be completed**

- [x] write unit tests 
- [x] implement favorite article functionality
- [x] implement unfavorite article functionality

**How can this be manually tested**

- Clone the repo and checkout the `ft/164857223-favorite-articles ` branch

- Create and activate a virtual environment
```
$ virtualenv env
$ source env/bin/activate
```

- Install requirements
```
$ pip install -r requirements.txt
```

- Make migrations
```
$ python manage.py makemigrations
```

- Run migrations

```
$ python manage.py migrate
```

- Run the tests
```
python manage.py test
```
- Test via Postman 

  * Favorite an article
    `[POST] http://127.0.0.1:8000/api/articles/<article-slug>/favorite`
   
  * unFavorite an article
    `[DELETE] http://127.0.0.1:8000/api/articles/<article-slug>/favorite`
    
   * Get Favorite Articles
  `[GET] http://127.0.0.1:8000/api/favorites`

    * Filter articles by favorited user
    `[GET] http://127.0.0.1:8000/api/articles?favorited_by=<username>`

**Relevant Pivotal tracker stories** 
[#164857223](https://www.pivotaltracker.com/story/show/164857223)

### Screenshots

**Favorite an article**
image

**Unfavorite an article**
image

**List favorite articles**
image

**List articles favorite stats**
image

**Filter articles by favorited_by**
image

### CODE REVIEW

**Review by misocho — COMMENTED** [review]
Could please update the get articles response message with favourited and favoritesCount fields as per the documentation so that we can know which articles have been favourited when getting an article.
Otherwise, the feature is working as expected.

image

**Comment by bencyn** [comment]
image


@misocho I've added the stats check it out

**Review by misocho — APPROVED** [review]
The feature works well on my end

**Review by martinMutuma — APPROVED** [review]
Would you consider changing this `/api/v1/favorites/` to `/api/v1/articles/favorites/` before it is merged 
Otherwise works as expected

**Comment by bencyn** [comment]
@martinMutuma  there  is a conflict of interest with  articles slug url ` url(r'^articles/(?P<slug>[-\w]+)/?$',
        SingleArticleView.asview(),
        name="single-article"),`

**Pull request merged**
