### PR TITLE
#164857215 Password Reset

### PR DESCRIPTION
**Pull request by misocho**
#### What does this PR do?
- Send the reset password link to the user's email
- Create the reset password endpoint
#### Description of Task to be completed?
- Send password reset link to user email
- Create the reset password endpoint
- Write tests for reset password endpoint
#### How should this be manually tested?
* Clone the repo
```
https://github.com/rfpremier/ah-django.git
```
* Navigate to the project directory
* Create and activate a virtual environment
```
$ virtualenv env
$ source env/bin/activate
```
* Checkout to `ft/164857215-password-reset` branch
```
$ git checkout ft/164857215-password-reset
```
* Install requirements
```
$ pip install -r requirements.txt
```
* Setup your local environment
```
$ source .env
```
* Make migrations
```
$ python manage.py makemigrations
```
* Run migrations
```
$ python manage.py migrate
```
* Start the app
```
$ python manage.py runserver
```
* Open Postman 
* If you don't have an account, signup on `[POST] http://127.0.0.1:8000/api/users/`
```
{
          "user": {
                "email": "validemailaddress@example.com", # this should be a working email address that you have access to
                "username": "your username",
                "password": "yourpassword123"
            }
        }
```
* Test the reset-password on `[POST] http://127.0.0.1:8000/api/users/password-reset/` 
* Use the following payload
```
{
	"user": {
			"email": "validemailaddress@example.com" # this should be a working email address that you have access to
	}
}
```
* You will receive the following response
```
{
    "status": 200,
    "token": "token",
    "uid": id,
    "message": "Check email to reset password"
}
```
* Check your email for the reset password url
* Test the url `[PATCH] http://127.0.0.1:8000/api/users/password-reset-confirm/?uid='{uid}&token='{token}'`with postman
* Fields required
```
{
	"new_password": "newpassword123",
	"re_new_password": "newpassword123"
}
```
* You will receive the following response
```
{
    "message": "Password reset successfully.",
    "status": 200
}
```
* Run tests
```
$ python manage.py test
```
#### What are the relevant pivotal tracker stories?
#164857215 
### Screenshots (if appropriate)
Screenshot_2019-03-28_10-11-45
Screenshot_2019-03-28_10-11-10

### CODE REVIEW

**Comment by Tevinthuku** [comment]
image

In your description, the password set fails because it contains characters that are not alphanumeric

**Comment by misocho** [comment]
Oh sorry about that... I thought the password accepted special characters @Tevinthuku

**Comment by misocho** [comment]
@Tevinthuku  And also when testing use a working email address that you have access to since the reset link will be sent to that email

**Comment by Tevinthuku** [comment]
Im getting a 401 error when I try to request for a password reset like so

image

Im using my own email address to test

**Comment by Tevinthuku** [comment]
I think I know where the problem is, I havent set the api key

**Review by martinMutuma — COMMENTED** [review]
Would you please add Http Methods to your PR request
eg [POST] api/password-reset/ and PATCH /api/password-reset-confirm/.
The Urls too, could is it possible to continue with the convection there?
``` url(r'^user/?$', UserRetrieveUpdateAPIView.as_view()),
    url(r'^users/?$', RegistrationAPIView.as_view()),
    url(r'^users/login/?$', LoginAPIView.as_view()),
    path('users/password-reset/', ResetPassword.as_view(), name='password_reset'),
    path('users/password-reset-confirm/', ResetPasswordConfirmView.as_view(),
         name='password_reset_confirm')
```

**Comment by misocho** [comment]
> Add Http Methods to your PR request
> eg [POST] api/password-reset/ and PATCH /api/password-reset-confirm
> The Urls too could is it possible to continue with the convection there?
> 
> ```
>     url(r'^users/?$', RegistrationAPIView.as_view()),
>     url(r'^users/login/?$', LoginAPIView.as_view()),
>     path('users/password-reset/', ResetPassword.as_view(), name='password_reset'),
>     path('users/password-reset-confirm/', ResetPasswordConfirmView.as_view(),
>          name='password_reset_confirm')
> ```

Okay I will thanks for the suggestion

**Comment by misocho** [comment]
@Tevinthuku  I have shared the API key at the channel

**Comment by Tevinthuku** [comment]
image

We are using jwt for token authentication. you can switch the token generation to using JWT

**Comment by Tevinthuku** [comment]
I've seen the email hits my mailbox which is awesome :+1: 

here's just some small things you can work on

1. Linting issues (autopep8) can help
image
2. The token sent in the email. 
I think since we are using JWT you can switch it from using the default token generator that django provides to generating one with flask. 
You can refer to this link below on how the token is generated
https://github.com/rfpremier/ah-django/blob/db4116d163eddf50e39dc124ad9f603d94de1207/authors/apps/authentication/models.py#L122

**Review by Tevinthuku — APPROVED** [review]
Looks good

**Review by martinMutuma — APPROVED** [review]
Looks Good and Works on my machine

**Review by miritih — APPROVED** [review]

**Review by justMuriithi — APPROVED** [review]

**Pull request merged**
