### PR TITLE
#164857226 Allows an author to tag their articles

### PR DESCRIPTION
**Pull request by justMuriithi**
### What does this PR do?
This PR introduces tagging articles functionality

### Tasks to be complete
 - [x] Writes tests for tag article 
 - [x] Allows an author to tag their article
 - [x] Allows an author to have the choice of not tagging their articles

### How can this be manually tested?
 
 - Clone the repo and checkout  `ft/164857226-tagging-articles ` branch
- Install a virtual environment and activate 
- Run `pip install -r requirements.txt`
 - Run `python manage.py makemigrations`
 - Run `python manage.py migrate`
- Run the dev server `python manage.py runserver`
 - Create a new account with the following details
- use postman to test following endpoints 
 `POST http://127.0.0.1:8000/api/users/`
     ```js
     {
     "user": {
       	"email": "profilemania@gmail.com",
		"password": "profiles2019",
		"username": "profmania"
    }
      }
     ```
- use the token from the signup to test the following endpoints 
`POST http://127.0.0.1:8000/api/articles`
```json 
{
	"article": {
		"title": "Premier2",
		"description": "Testing2",
		"body": "sentence1, sentence2",
		"image_url": "http://www.google.com"
		}
	
}
```
- response
```json 
{
    "id": 1,
    "title": "Premier2",
    "description": "Testing2",
    "body": "sentence1, sentence2",
    "image_url": "http://www.google.com",
    "author": 1,
    "created_at": "2019-04-04",
    "slug": "premier2-2",
    "avg_rating": 0,
    "rating_count": 0,
    "tags": []
}
```
#### OR
- use the token from the signup to test the following endpoints 
`POST http://127.0.0.1:8000/api/articles`
```json 
{
	"article": {
		"title": "Premier2",
		"description": "Testing2",
		"body": "sentence1, sentence2",
		"image_url": "http://www.google.com",
                "tags": ["test", "trial"]
		}
	
}
```
- response
```json 
{
    "id": 1,
    "title": "Premier2",
    "description": "Testing2",
    "body": "sentence1, sentence2",
    "image_url": "http://www.google.com",
    "author": 1,
    "created_at": "2019-04-04",
    "slug": "premier2-2",
    "avg_rating": 0,
    "rating_count": 0,
    "tags": [
               "test",
               "trial"
     ]
}
```
- use postman to test the following endpoint to get a list of all tags
`GET http://127.0.0.1:8000/api/tags`
- response
```json
{
    "tags": [
        "test",
       "trial"
    ]
}
```

### Any background context
N/A
 ### PT stories relevant to this PR?
 [#164857226](https://www.pivotaltracker.com/n/projects/2321565/stories/164857226)

### Screenshots
Screenshot from 2019-04-09 23-06-54
Screenshot from 2019-04-09 23-07-53
Screenshot from 2019-04-11 16-05-11

### CODE REVIEW

**Review by bencyn — COMMENTED** [review]
Tested on my end. Works as expected. Good job

**Review by misocho — COMMENTED** [review]
Works well. Maybe you could add the endpoint for getting all tags as per the documentation.

image

**Comment by justMuriithi** [comment]
> Works well. Maybe you could add the endpoint for getting all tags as per the documentation.
> 
> image

GET /api/tags now up and running

**Review by misocho — APPROVED** [review]

**Review by Tevinthuku — APPROVED** [review]
Nice work :+1: . everything works as expected

**Review by miritih — APPROVED** [review]

**Pull request merged**
