### PR TITLE
#164857222 follow & unfollow authors

### PR DESCRIPTION
**Pull request by Tevinthuku**
### What does this PR do?
This PR introduces the follow and unfollow functionality into the app.

### Tasks to be completed

- [x] - Add tests for follow functionality
- [x] - Add follow and view followers functionality
- [x] - Create following view
- [x] - Add tests for unfollow functionality
- [x] - Create unfollow functionality
 
 ### How can this be manually test?
 
 - Clone the repo and checkout to the `ft/164857222-follow-n-unfollow` branch
 - Run `python manage.py makemigrations`
 - Run `python manage.py migrate`
 - Create a 2 new account with the following details
	 - First User
	 `POST http://127.0.0.1:8000/api/users/`
	     ```js
	     {
	     "user": {
	       	"email": "profilemania@gmail.com",
			"password": "profiles2019",
			"username": "profmania"
	    }
	      }
	     ```
	     -  Second User
	     	 `POST http://127.0.0.1:8000/api/users/`
		     ```js
		     {
		     "user": {
		       	"email": "profilemania2@gmail.com",
				"password": "profiles2019",
				"username": "profmania2"
			     }
		      }
			```
- Let the new author `profmania2` follow `profmania`

`POST http://127.0.0.1:8000/api/users/profmania/follow/`
Note: Let `profmania2's` token be in the authorization headers.

You will get the following results
```js
{
    "following": {
        "image": "",
        "bio": "",
        "username": "profmania",
        "firstname": "",
        "lastname": "",
        "fullname": " "
    }
}
```

- To see a list of those that follow `profmania`
`GET http://127.0.0.1:8000/api/users/profmania/followers/`

You will get the following response
```js
{
    "followers": [
        {
            "image": "",
            "bio": "",
            "username": "profmania2",
            "firstname": "",
            "lastname": "",
            "fullname": " "
        }
    ]
}
```

- To see a list of who `profmania` follows
`GET http://127.0.0.1:8000/api/users/profmania/following/`

You get the following response
```js
{
    "following": []
}
```

This is because as of this point `profmania` hasn't followed anyone.

### Any background context
Scenarios that won't work
1. An attempt to follow a user for a second time
2. An attempt to follow a user that does not exist
3. An attempt to unfollow a user you did not follow
4. An attempt to unfollow a non-existent user

### Screenshots

On viewing a list of profiles you can now see a `following` property that states if the user is viewing the profiles follows the various authors present or not.

image

image

 ### PT stories relevant to this PR?
 [#164857222](https://www.pivotaltracker.com/n/projects/2321565/stories/164857222)

### CODE REVIEW

**Review by misocho — COMMENTED** [review]
Works well, good job. Maybe you could update the get profile to display whether you are following a user.
image

**Comment by Tevinthuku** [comment]
@misocho I missed that, I'll add it and let you know when I'm done

**Comment by Tevinthuku** [comment]
Done :ballot_box_with_check:

**Comment by Tevinthuku** [comment]
> @misocho I missed that, I'll add it and let you know when I'm done

Done :ballot_box_with_check:

**Review by Kimaiyo077 — APPROVED** [review]
Everything works as expected. Nice work

**Review by misocho — APPROVED** [review]

**Review by miritih — APPROVED** [review]

**Pull request merged**
