### PR TITLE
#164857232 create bookmarking functionality

### PR DESCRIPTION
**Pull request by Tevinthuku**
### What does this PR do?
This PR adds the bookmarking and unbookmarking of an article functionality

### Tasks to be completed?

 - [x] create the bookmark model

- [x]  remove unnecessary config files  
  
- [x] write bookmark tests  
  
- [x] add uniqueness constraint  
  
- [x] create bookmark serializer  
  
- [x] create bookmark creation view  
  
- [x] make responses human readable  
  
- [x] write tests for viewing all article bookmarkers  
  
- [x] create endpoint to view all bookmarkers profiles  
  
- [x] write tests to unbookmark an article  
  
- [x] Create unbookmark functionality

### How can this be manually tested?
1. Clone this repo.
2. Checkout to the `ft/164857232-bookmark-articles`
3. Run `python manage.py makemigrations` & `python manage.py migrate`
4. Create a new user via the `POST http://127.0.0.1:8000/api/users/`
```js
{
   "user": {
  	 "email": "bookmarker@gmail.com",
     "password": "bookmark2019",
     "username": "bookmark"
    }
 }
```
5. Create a new article
   `POST http://127.0.0.1:8000/api/articles`
N/B: Remember to have the user token in the Authorization field
```js
{
	"article": {
		"title": "Article to be bookmarked",
		"description": "Article 2 be bookmarked.",
		"body": "bookmarking & unbookmarking",
		"image_url": "http://www.google.com"
		}
}
```

N/B: The unique article identifier on the URLS below is the slug, not the title

6. To bookmark the article
`POST http://127.0.0.1:8000/api/articles/article-to-be-bookmarked/bookmarks/`
You will the following response
```js
{
  "data": "You have successfully bookmarked Article to be bookmarked"
}
``` 

7. To unbookmark an article
`DELETE http://127.0.0.1:8000/api/articles/article-to-be-bookmarked/bookmarks/`

You get the following response

```js
{
    "data": "You have successfully unbookmarked Article to be bookmarked"
}
```

8. To view all the articles you have bookmarked. 
`GET http://127.0.0.1:8000/api/bookmarks/articles/`
Remember to have the auth token in your headers

```json
{
    "articles": [
        {
            "id": 1,
            "title": "Article to be bookmarked",
            "description": "Article 2 be bookmarked.",
            "body": "bookmarking & unbookmarking",
            "image_url": "http://www.google.com",
            "author": {
                "username": "bookmark",
                "bio": "",
                "image": ""
            },
            "created_at": "2019-04-17T14:05:45.842287Z",
            "updated_at": "2019-04-17T14:05:45.842338Z",
            "slug": "article-to-be-bookmarked",
            "avg_rating": 0,
            "rating_count": 0,
            "tags": [],
            "favorited": false,
            "favoritesCount": 0
        }
    ]
}

```

9. To view a list of everyone that bookmarked an article
`GET http://127.0.0.1:8000/api/articles/article-to-be-bookmarked/bookmarks/`

You get the following response.
You see their profile and also the time they bookmarked the article.
```js
{
    "bookmarkers": [
        {
            "profile": {
                "image": "",
                "bio": "",
                "id": 2,
                "username": "bookmark",
                "firstname": "",
                "following": false,
                "lastname": "",
                "fullname": " "
            },
            "created_at": "2019-04-16T07:05:22.452907Z"
        }
    ]
}
```

### Any background context you want to add?
1. You cannot bookmark an article twice. If you attempt to do so you will get the following response
```js
{
    "error": "You already bookmarked Article to be bookmarked"
}
```
2. You also cannot un-bookmark an article twice if you attempt to do so you will get the following error

```js
{
    "error": "You had not bookmarked Article to be bookmarked"
}
```

### Screenshots

image

image

image

image

- On attempting to bookmark and un-bookmark multiple times

image

image

### CODE REVIEW

**Review by bencyn — COMMENTED** [review]
Kindly update your URL descriptions such as `http://127.0.0.1:8000/api/articles/article-to-be-bookmarked/bookmark/` to something like `http://127.0.0.1:8000/api/articles/<article-slug>/bookmark/`. It's quite unclear whether one should use the article title or the article slug.

**Comment by Tevinthuku** [comment]
> Kindly update your URL descriptions such as `http://127.0.0.1:8000/api/articles/article-to-be-bookmarked/bookmark/` to something like `http://127.0.0.1:8000/api/articles/<article-slug>/bookmark/`. It's quite unclear whether one should use the article title or the article slug.

I've updated it, though we use the slug for all article operations. I've had it that way since its a follow through example.I didn't want to give reviewers a hard time

**Review by justMuriithi — APPROVED** [review]
I really like this. Particularly the ability to view the bookmakers of your article.

**Review by martinMutuma — APPROVED** [review]
Works as expected

**Pull request merged**
