### PR TITLE
#164857231 Social sharing

### PR DESCRIPTION
**Pull request by justMuriithi**
### What does this PR do?
This PR introduces social sharing articles functionality

### Tasks to be completed
 - [x] Writes tests for sharing of articles by email, facebook and twitter
 - [x] Implements sharing of articles by email, facebook and twitter
 - [x] Adds an email template for sharing of articles by email

### How can this be manually tested?
 
 - Clone the repo and checkout  `ft/164857231-social-sharing ` branch
- Install a virtual environment and activate 
- Run `pip install -r requirements.txt`
 - Run `python manage.py makemigrations`
 - Run `python manage.py migrate`
- Run the dev server `python manage.py runserver`
 - Create a new account with the following details
- use postman to test following endpoints 
 `POST http://127.0.0.1:8000/api/users/`
     ```js
     {
     "user": {
       	"email": "profilemania@gmail.com",
		"password": "profiles2019",
		"username": "profmania"
    }
      }
     ```
- use the token from the signup to test the following endpoints 
`POST http://127.0.0.1:8000/api/articles`
```json 
{
	"article": {
		"title": "Premier2",
		"description": "Testing2",
		"body": "sentence1, sentence2",
		"image_url": "http://www.google.com"
		}
	
}
```
- response
```json 
{
    "article": {
        "id": 3,
        "title": "Premier2",
        "description": "Testing2",
        "body": "sentence1, sentence2",
        "image_url": "http://www.google.com",
        "author": {
            "username": "profmania",
            "bio": "",
            "image": ""
        },
        "created_at": "2019-04-16T11:09:21.146077Z",
        "updated_at": "2019-04-16T11:09:21.146113Z",
        "slug": "premier2",
        "avg_rating": 0,
        "rating_count": 0,
        "tags": [],
        "favorited": false,
        "favoritesCount": 0
    }
}
```
- use the token from the signup to test share by email 
`POST http://127.0.0.1:8000/api/articles/premier2/share/email/`
```json 
{
	"email": "tonywamuriithi@gmail.com"
}
```
- response
```json 
{
    "message": "Article shared successfully",
    "shared_link": "http://127.0.0.1:8000/api/articles/premier2"
}
```
- use the token from the signup to test share by facebook 
`POST http://127.0.0.1:8000/api/articles/premier2/share/facebook/`
- response
```json
{
    "message": "Article shared successfully",
    "shared_link": "https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/api/articles/premier2"
}
```
- use the token from the signup to test share by twitter 
`POST http://127.0.0.1:8000/api/articles/premier2/share/twitter/`
- response 
```json
{
    "message": "Article shared successfully",
    "shared_link": "https://twitter.com/intent/tweet?text=http://127.0.0.1:8000/api/articles/premier2"
}
```
### Any background context
N/A
 ### PT stories relevant to this PR?
 [#164857231](https://www.pivotaltracker.com/n/projects/2321565/stories/164857231)

### Screenshots
Screenshot from 2019-04-16 13-24-41
Screenshot from 2019-04-16 13-33-26
Screenshot from 2019-04-16 13-35-35
Screenshot from 2019-04-16 13-36-29
Screenshot from 2019-04-16 13-38-01
Screenshot from 2019-04-16 13-38-59
Screenshot from 2019-04-16 13-40-36

### CODE REVIEW

**Comment by Tevinthuku** [comment]
Nice work,
I like the styling of the sharing email and it works well in facebook, but I'm encountering a challenge in twitter, it's not prompting me to tweet about the article

image

Maybe the twitter response could be

```
https://twitter.com/intent/tweet?text=the article in question
```

**Comment by justMuriithi** [comment]
> Nice work,
> I like the styling of the sharing email and it works well in facebook, but I'm encountering a challenge in twitter, it's not prompting me to tweet about the article
> 
> image
> 
> Maybe the twitter response could be
> 
> ```
> https://twitter.com/intent/tweet?text=the article in question
> ```

Do have another try at it. It seems to be working great on the 4 devices I've tested it on.

**Comment by Tevinthuku** [comment]
> > Nice work,
> > I like the styling of the sharing email and it works well in facebook, but I'm encountering a challenge in twitter, it's not prompting me to tweet about the article
> > image
> > Maybe the twitter response could be
> > ```
> > https://twitter.com/intent/tweet?text=the article in question
> > ```
> 
> Do have another try at it. It seems to be working great on the 4 devices I've tested it on.

I've tried it on Firefox, it works as expected before updating to the new twitter look
image

Once updated it doesn't work anymore
image

**Comment by justMuriithi** [comment]
> > Nice work,
> > I like the styling of the sharing email and it works well in facebook, but I'm encountering a challenge in twitter, it's not prompting me to tweet about the article
> > image
> > Maybe the twitter response could be
> > ```
> > https://twitter.com/intent/tweet?text=the article in question
> > ```
> 
> Do have another try at it. It seems to be working great on the 4 devices I've tested it on.

I've had a look at it. It indeed doesn't work on the new look of Twitter. Let me refactor to find a means that will work for both legacy twitter and the new one as well.

**Comment by Tevinthuku** [comment]
It won't be much refactoring
```
{
    "message": "Article shared successfully",
    "shared_link": "https://twitter.com/intent/tweet?text=http://127.0.0.1:8000/api/articles/premier2"
}
```
I've tested this out and it works, you can refactor the `shared_link` to that format and it will work for both old and new twitter versions

**Review by Tevinthuku — APPROVED** [review]
Works like a charm across all platforms now :+1: , awesome work

**Comment by justMuriithi** [comment]
> It won't be much refactoring
> 
> ```
> {
>     "message": "Article shared successfully",
>     "shared_link": "https://twitter.com/intent/tweet?text=http://127.0.0.1:8000/api/articles/premier2"
> }
> ```
> I've tested this out and it works, you can refactor the `shared_link` to that format and it will work for both old and new twitter versions

That's exactly what I've switched it to. Thanks for catching it. Already pushed the changes. Tested with legacy and the new look. Works great!

**Review by martinMutuma — APPROVED** [review]
Works as said

**Pull request merged**
