### PR TITLE
#164981399 Email refactor and unspam

### PR DESCRIPTION
**Pull request by misocho**
#### What does this PR do?
- Refactor send email method
- Ensure reset password email does to the inbox
#### Description of Task to be completed?
- Refactor send email method
- Ensure reset password email does to the inbox
#### How should this be manually tested?
- Clone the repo
- Navigate to the project directory
- Create and activate a virtual environment
```
$ virtualenv env
$ source env/bin/activate
```
- Setup environment variables
```
$ source .env
```
- Make migrations
```
$ python manage.py makemigrations
```
- Run migrations
```
$ python manage.py migrate
```
- Open Postman and test the endpoints
- If you don't have an account signup
```
{
          "user": {
                "email": "validemailaddress@example.com", # this should be a working email address that you have access to
                "username": "your username",
                "password": "yourpassword123"
            }
        }
```
* Test the reset-password on `[POST] http://127.0.0.1:8000/api/users/password-reset/` 
* Use the following payload
```
{
	"user": {
			"email": "validemailaddress@example.com" # this should be a working email address that you have access to
	}
}
```
* You will receive the following response
```
{
    "status": 200,
    "token": "token",
    "uid": id,
    "message": "Check email to reset password"
}
```
* Check your email the reset password url should be in the inbox folder
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/164981399
#### Screenshots
image

### CODE REVIEW

**Review by Kimaiyo077 — APPROVED** [review]
All the emails are being delivered to my inbox as expected. Great job

**Review by justMuriithi — APPROVED** [review]
Both the email notification on sign up and reset password emails are going straight to inbox. Good job.

**Review by bencyn — COMMENTED** [review]
Confirmed both email notifications on user signup and reset password are going straight to inbox.

image

image

Great work.

**Review by miritih — APPROVED** [review]
Good job @misocho

**Pull request merged**
